Feat/listen something machine
butia-bots/butia_behavior pull request #16
Opened 2022-09-08 17:13 UTC by PedroCorcaque

- getListenSomethingMachine implemented;
- ServiceCallerState changed;

2022-09-09 21:13 UTC, igormaurell requested changes

2022-09-09 21:13 UTC, igormaurell commented on src/butia_behavior/machines/listen_something.py
> +        smach.StateMachine.add(
There is no need of call audio player. The speech to text service already plays the beep audio.

2022-09-09 21:13 UTC, igormaurell commented on src/butia_behavior/machines/say_something.py
> +                            input_keys=["text"])
This part may generate an error. The problem is: text to speech service needs a field called 'lang'; in the case of using userdata, from where it comes?

2022-09-09 21:13 UTC, igormaurell commented on src/butia_behavior/states/service_caller.py
> +    response_dict = ServiceCallerState.convertResponseToDict(response)
I thing that just one function that directly converts from response to userdata is more straight foward.

2022-09-10 17:05 UTC, PedroCorcaque commented on src/butia_behavior/machines/say_something.py
> +                            input_keys=["text"])
Added the "lang" parameter in input_keys to receive information by userdata too.

Commit [60b8f7d](https://github.com/butia-bots/butia_behavior/pull/16/commits/60b8f7df33672c313a2b43ac0d86b29ef2666df5)

2022-09-10 17:09 UTC, PedroCorcaque commented on src/butia_behavior/machines/listen_something.py
> +        smach.StateMachine.add(
Removed the AudioPlayer call in the getListenSomethingMachine. 

Commit [0454eab](https://github.com/butia-bots/butia_behavior/pull/16/commits/0454eaba9bf85a5502a077e8d1a0e15d9b783268)

2022-09-12 13:43 UTC, igormaurell commented on src/butia_behavior/machines/say_something.py
> +                            input_keys=["text"])
I think that we will never use the lang param on userdata. A better solution is to keep lang as a constructor parameter of SaySomethingMachine and use a state to add it to the userdata to be used by ServiceCaller.

2022-09-12 18:07 UTC, PedroCorcaque commented on src/butia_behavior/machines/say_something.py
> +                            input_keys=["text"])
I added the lang param as input_keys because I think that the parameter can come from ListenSomethingMachine in future. We can to make the speech_recognizer returns the lang too.

By the way, your suggestion is to create a new state to just add the lang param in the userdata? Inside of SaySomethingMachine?

2022-09-12 19:11 UTC, PedroCorcaque commented on src/butia_behavior/states/service_caller.py
> +    response_dict = ServiceCallerState.convertResponseToDict(response)
The convertResponseToDict function was removed. Now the ~convertResponseDictToUserdata~ convertResponseToUserdata receives the response object and creates the userdata attributes.

Commit [a5ff62e](https://github.com/butia-bots/butia_behavior/pull/16/commits/a5ff62e7779b0e6241478727560827d670f0ea0e)

2022-09-13 17:44 UTC, igormaurell approved these changes

2022-09-13 17:44 UTC, merged